# Generated by Django 5.2.14 on 2026-06-23 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_default_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-is_best_seller', '-is_featured', 'name'), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'категория товара', 'verbose_name_plural': 'категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'особенность товара', 'verbose_name_plural': 'особенности товара'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'медиа товара', 'verbose_name_plural': 'медиа товаров'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'характеристика товара', 'verbose_name_plural': 'характеристики товара'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=80, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, verbose_name='сайт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('low_stock', 'Мало на складе'), ('out_of_stock', 'Нет в наличии'), ('preorder', 'Предзаказ'), ('discontinued', 'Снят с продажи')], default='in_stock', max_length=20, verbose_name='статус наличия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD')], default='KGS', max_length=3, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='хит продаж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='подборка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=180, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='остаток на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата релиза'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=280, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, verbose_name='гарантия, мес.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='вес, г'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='device_type',
            field=models.CharField(choices=[('mouse', 'Мышь'), ('keyboard', 'Клавиатура'), ('headset', 'Гарнитура'), ('mousepad', 'Коврик'), ('controller', 'Контроллер'), ('monitor', 'Монитор'), ('component', 'Компонент'), ('accessory', 'Аксессуар'), ('other', 'Другое')], default='other', max_length=24, verbose_name='тип устройства'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='description',
            field=models.CharField(blank=True, max_length=280, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title',
            field=models.CharField(max_length=140, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='alt текст'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, upload_to='products/media/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='основное'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='тип медиа'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='products.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, max_length=80, verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='is_highlight',
            field=models.BooleanField(default=False, verbose_name='показывать как ключевую'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='unit',
            field=models.CharField(blank=True, max_length=32, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=255, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Логическое')], default='text', max_length=16, verbose_name='тип значения'),
        ),
    ]
