# Generated by Django 5.2.14 on 2026-06-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
