# Generated by Django 5.2.14 on 2026-06-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcoloroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechnicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(blank=True, max_length=120, verbose_name='форм-фактор')),
                ('connectivity', models.CharField(blank=True, max_length=120, verbose_name='подключение')),
                ('compatibility', models.CharField(blank=True, max_length=160, verbose_name='совместимость')),
                ('software_support', models.CharField(blank=True, max_length=160, verbose_name='ПО / драйверы')),
                ('battery_life_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='автономность, ч')),
                ('cable_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='длина кабеля, м')),
                ('sensor_model', models.CharField(blank=True, max_length=120, verbose_name='сенсор')),
                ('dpi', models.PositiveIntegerField(blank=True, null=True, verbose_name='DPI')),
                ('polling_rate_hz', models.PositiveIntegerField(blank=True, null=True, verbose_name='polling rate, Гц')),
                ('response_time_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='время отклика, мс')),
                ('switch_type', models.CharField(blank=True, max_length=120, verbose_name='тип переключателей')),
                ('programmable_buttons', models.PositiveIntegerField(blank=True, null=True, verbose_name='программируемые кнопки')),
                ('keyboard_layout', models.CharField(blank=True, max_length=120, verbose_name='раскладка / формат')),
                ('key_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество клавиш')),
                ('switch_profile', models.CharField(blank=True, max_length=120, verbose_name='профиль свитчей')),
                ('hot_swap', models.BooleanField(default=False, verbose_name='hot-swap')),
                ('backlight', models.CharField(blank=True, max_length=120, verbose_name='подсветка')),
                ('driver_size_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='диаметр драйверов, мм')),
                ('microphone', models.CharField(blank=True, max_length=120, verbose_name='микрофон')),
                ('surround_sound', models.CharField(blank=True, max_length=120, verbose_name='звук / surround')),
                ('frequency_response', models.CharField(blank=True, max_length=120, verbose_name='частотный диапазон')),
                ('impedance_ohm', models.PositiveIntegerField(blank=True, null=True, verbose_name='сопротивление, Ом')),
                ('sensitivity_db', models.PositiveIntegerField(blank=True, null=True, verbose_name='чувствительность, дБ')),
                ('surface_type', models.CharField(blank=True, max_length=120, verbose_name='тип поверхности')),
                ('pad_size', models.CharField(blank=True, max_length=120, verbose_name='размер коврика')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='толщина, мм')),
                ('stitched_edges', models.BooleanField(default=False, verbose_name='прошитые края')),
                ('base_material', models.CharField(blank=True, max_length=120, verbose_name='основание')),
                ('panel_type', models.CharField(blank=True, max_length=120, verbose_name='тип матрицы')),
                ('resolution', models.CharField(blank=True, max_length=120, verbose_name='разрешение')),
                ('refresh_rate_hz', models.PositiveIntegerField(blank=True, null=True, verbose_name='частота обновления, Гц')),
                ('brightness_nits', models.PositiveIntegerField(blank=True, null=True, verbose_name='яркость, нит')),
                ('contrast_ratio', models.CharField(blank=True, max_length=120, verbose_name='контрастность')),
                ('material', models.CharField(blank=True, max_length=120, verbose_name='материал')),
                ('extra_notes', models.CharField(blank=True, max_length=255, verbose_name='дополнительно')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_details', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'технический профиль товара',
                'verbose_name_plural': 'технические профили товаров',
            },
        ),
    ]
