# Generated by Django 5.2.14 on 2026-07-20 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producttechnicaldetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='ru', max_length=2, verbose_name='язык')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('notified', 'Уведомлен'), ('cancelled', 'Отменена')], default='active', max_length=16, verbose_name='статус')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='уведомлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_subscriptions', to='products.product', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подписка на поступление',
                'verbose_name_plural': 'подписки на поступление',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_product_stock_subscription')],
            },
        ),
    ]
