# Generated by Django 5.2.14 on 2026-06-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['locale'], 'verbose_name': 'контактная информация', 'verbose_name_plural': 'контактная информация'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text_en',
            field=models.TextField(verbose_name='текст (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text_kg',
            field=models.TextField(verbose_name='текст (KG)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text_ru',
            field=models.TextField(verbose_name='текст (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='заголовок (KG)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/videos/', verbose_name='видео'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='extra_contacts',
            field=models.JSONField(blank=True, default=dict, verbose_name='дополнительные контакты'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='locale',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kg', 'Кыргызский')], max_length=2, unique=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='часы работы'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
