# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('kg', 'Kyrgyz')], default='ru', max_length=2)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
