# Generated by Django 5.2.14 on 2026-07-20 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contactmessage_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('notification_type', models.CharField(choices=[('stock', 'Поступление товара'), ('order', 'Заказ'), ('promotion', 'Акция'), ('system', 'Системное')], default='system', max_length=20, verbose_name='тип')),
                ('status', models.CharField(choices=[('unread', 'Не просмотрено'), ('read', 'Просмотрено'), ('archived', 'В архиве')], default='unread', max_length=16, verbose_name='статус')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='ссылка')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='изображение')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='дополнительные данные')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='просмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='users_notif_user_id_cfb1c7_idx')],
            },
        ),
    ]
